{{- if .Values.role.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
{{ toYaml .Values.global.labels | indent 4 }}
  name: {{ .Values.roleBinding.name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.role.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
{{- end }}
